
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrationapi1
    username: root
    password: Um@ahsan00
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect